INSERT INTO jungle.animal VALUES ('0', 'Rabbit', '4');
INSERT INTO jungle.animal VALUES ('1', 'Bear', '4');
INSERT INTO jungle.animal VALUES ('2', 'Deer', '4');
INSERT INTO jungle.animal VALUES ('3', 'Snake', '0');
INSERT INTO jungle.animal VALUES ('4', 'Coocodrile', '4');
INSERT INTO jungle.animal VALUES ('5', 'Chicken', '2');
INSERT INTO jungle.animal VALUES ('6', 'Spider', '8');


INSERT INTO jungle.food VALUES ('0', 'carrot');
INSERT INTO jungle.food VALUES ('1', 'honey');
INSERT INTO jungle.food VALUES ('2', 'leafs');
INSERT INTO jungle.food VALUES ('3', 'insects');
INSERT INTO jungle.food VALUES ('4', 'vermin');
INSERT INTO jungle.food VALUES ('5', 'birdseed');

INSERT INTO jungle.eat VALUES ('Rabbit', 'carrot');
INSERT INTO jungle.eat VALUES ('Rabbit', 'honey');
INSERT INTO jungle.eat VALUES ('Rabbit', 'leafs');
INSERT INTO jungle.eat VALUES ('Rabbit', 'insects');
INSERT INTO jungle.eat VALUES ('Rabbit', 'vermin');
INSERT INTO jungle.eat VALUES ('Rabbit', 'birdseed');
INSERT INTO jungle.eat VALUES ('Bear', 'carrot');
INSERT INTO jungle.eat VALUES ('Bear', 'honey');
INSERT INTO jungle.eat VALUES ('Bear', 'leafs');
INSERT INTO jungle.eat VALUES ('Bear', 'insects');
INSERT INTO jungle.eat VALUES ('Bear', 'vermin');
INSERT INTO jungle.eat VALUES ('Bear', 'birdseed');
INSERT INTO jungle.eat VALUES ('Deer', 'carrot');
INSERT INTO jungle.eat VALUES ('Deer', 'honey');
INSERT INTO jungle.eat VALUES ('Deer', 'leafs');
INSERT INTO jungle.eat VALUES ('Deer', 'insects');
INSERT INTO jungle.eat VALUES ('Deer', 'vermin');
INSERT INTO jungle.eat VALUES ('Deer', 'birdseed');
INSERT INTO jungle.eat VALUES ('Snake', 'carrot');
INSERT INTO jungle.eat VALUES ('Snake', 'honey');
INSERT INTO jungle.eat VALUES ('Snake', 'leafs');
INSERT INTO jungle.eat VALUES ('Snake', 'insects');
INSERT INTO jungle.eat VALUES ('Snake', 'vermin');
INSERT INTO jungle.eat VALUES ('Snake', 'birdseed');
INSERT INTO jungle.eat VALUES ('Coocodrile', 'carrot');
INSERT INTO jungle.eat VALUES ('Coocodrile', 'honey');
INSERT INTO jungle.eat VALUES ('Coocodrile', 'leafs');
INSERT INTO jungle.eat VALUES ('Coocodrile', 'insects');
INSERT INTO jungle.eat VALUES ('Coocodrile', 'vermin');
INSERT INTO jungle.eat VALUES ('Coocodrile', 'birdseed');
INSERT INTO jungle.eat VALUES ('Chicken', 'carrot');
INSERT INTO jungle.eat VALUES ('Chicken', 'honey');
INSERT INTO jungle.eat VALUES ('Chicken', 'leafs');
INSERT INTO jungle.eat VALUES ('Chicken', 'insects');
INSERT INTO jungle.eat VALUES ('Chicken', 'vermin');
INSERT INTO jungle.eat VALUES ('Chicken', 'birdseed');
INSERT INTO jungle.eat VALUES ('Spider', 'carrot');
INSERT INTO jungle.eat VALUES ('Spider', 'honey');
INSERT INTO jungle.eat VALUES ('Spider', 'leafs');
INSERT INTO jungle.eat VALUES ('Spider', 'insects');
INSERT INTO jungle.eat VALUES ('Spider', 'vermin');
INSERT INTO jungle.eat VALUES ('Spider', 'birdseed');